<?php
function slider1(){ ?>



<?php }

function slider2(){ ?>
	<div class="container">
        <div class="row">
            <div class="span9"> 
                <!-- Slider Start-->
                <section class="slider">
                    <!-- Start WOWSlider.com HEAD section -->
						<link rel="stylesheet" type="text/css" href="aset/noble-fade/engine1/style.css" media="screen" />
						<script type="text/javascript" src="aset/noble-fade/jquery.js"></script>
						<!-- End WOWSlider.com HEAD section -->
						<!-- ***************** - START Content - ***************** -->
						<!-- Start WOWSlider.com BODY section -->
							<div id="wowslider-container1">
							<div class="ws_images"><ul>
							<?php
							$sql=mysql_query('SELECT * FROM banner ORDER BY NO_URUT');
							while($data=mysql_fetch_array($sql)){
							?>
							<li><img src="admin/img/banner/<?php echo $data['GAMBAR']; ?>" alt="Azzahra Hijab Kerudung Masa Kini"  id="wows1_0"/></li>
							<?php } ?>
						</ul></div>

						<!-- Generated by WOWSlider.com v2.5 -->
						<div class="ws_shadow"></div>
						</div>
						<script type="text/javascript" src="aset/noble-fade/wowslider.js"></script>
						<script type="text/javascript" src="aset/noble-fade/engine1/script.js"></script>
						<!-- End WOWSlider.com BODY section -->
                </section>
                <!-- Slider End--> 
            </div>
            <aside class="span3"> 
                <!-- Category-->
                <div class="sidewidt">
                    <h2 class="heading2"><span><i class="icon-th-list"></i> Kategori</span></h2>
                    <ul class="nav nav-list categories">
						<?php
							$sql3=mysql_query('SELECT * FROM kategori ORDER BY KODE_KATEGORI');
							while($data3=mysql_fetch_array($sql3)){
						?>
                        <li> <a href="kategori.php"><?php echo $data3['NAMA_KATEGORI']; ?></a> </li>
						<?php } ?>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
<?php }?>


<?php function slider(){ ?>
<!-- Slider Start-->
    <section class="slider container">
        <div id="layerslider-container">
            <div id="layerslider1" style="width: 1200px; height: 550px; margin: 0 auto;">
                
                
                <div class="ls-layer" style="slidedelay: 7000; transition2d: 76,77,78,79; "> 
                	<img src="layerslider/gallery/bg3.jpg" class="ls-bg" alt="Slide background"> 
                    <img class="ls-s-1" src="layerslider/gallery/tucan.png" alt="Tucan" style="top: 25px; left: 550px; slidedirection : right; slideoutdirection : bottom; durationin : 4000; easingin : easeOutQuart;  rotateout : -10; scalein : 1.2; ">
                    <h5 class="ls-s3 text-b br5" style="top:50%; left: 30%; slidedirection : fade; slideoutdirection : right; durationin : 6000; easingout : easeInQuart; rotateout : 35; scaleout : 5; showuntil : 701;"> Trend </h5>
                    <h5 class="ls-s3 text-c br5" style="top:58%; left: 25%; slidedirection : fade; slideoutdirection : right; durationin : 6000; easingout : easeInQuart; delayin : 250; rotateout : 35; scaleout : 5; showuntil : 351;"> Hijab </h5>
                    <h5 class="ls-s4 text-d br5" style="top:70%; left: 35%; slidedirection : fade; slideoutdirection : right; durationin : 6000; easingout : easeInQuart; delayin : 500; rotateout : 35; scaleout : 5; showuntil : 1;"> 2014 </h5>
                    
                    <a class="ls-s3 br5 c black" href="#"  style="top:180px; left: 25%; slidedirection : fade; durationin : 2000; delayin : 2500; rotatein : -90; rotateout : -90;  scaleout : 0; padding:0 10px"> Bahan Terbaik & Berkualitas </a> 
                </div>  
                
               
                  <div class="ls-layer" style="slidedelay: 10000; transition2d: 11; "> 
                  	<img src="layerslider/gallery/bg3.jpg" class="ls-bg" alt="Slide background">
                	<h5 class="ls-s3 text-c br5" style="top:58%; left: 25%; slidedirection : left; slideoutdirection : bottom; durationin : 500; easingout : easeInQuart; delayin : 100; rotateout : 35; scaleout : 5; showuntil : 9000;"> Dengan Berbagai Model</h5>
                    <h5 class="ls-s4 text-d br5" style="top:70%; left: 22%; slidedirection : left; slideoutdirection : bottom; durationin : 700; easingout : easeInQuart; delayin : 200; rotateout : 35; scaleout : 5; showuntil : 9000;"> Dan Pilihan Warna </h5>
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-3.png" alt="Clown Fish" style="top: 40%; left: 60%; slidedirection : top; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 1000; showuntil : 1; ">
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-2.png" alt="Blue Sergeonfish" style="top: 60%; left: 60%; slidedirection : bottom; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 2500; showuntil : 1; ">
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-1.png" alt="Yellow Tang" style="top: 40%; left: 60%; slidedirection : top; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 4000; showuntil : 1;"> 
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-4.png" alt="Yellow Tang" style="top: 60%; left: 60%; slidedirection : bottom; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 5500; showuntil : 1;"> 
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-5.png" alt="Yellow Tang" style="top: 40%; left: 60%; slidedirection : top; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 7000; showuntil : 1;"> 
                    
                    <img class="ls-s2" src="layerslider/gallery/fish-showcase-6.png" alt="Yellow Tang" style="top: 60%; left: 60%; slidedirection : bottom; slideoutdirection : right; durationin : 750; easingin : easeOutQuart; easingout : easeInQuart; delayin : 8500;"> 
                
                </div> 
                
                
                <div class="ls-layer" style="slidedelay: 13000; transition2d: 105; "> <img src="layerslider/gallery/bg3.jpg" class="ls-bg" alt="Slide background">
                    <h5 class="ls-s3 text-a br5" style="top:-30px; left: -100px; slidedirection : fade; slideoutdirection : fade; scalein : 0.5; scaleout : 0.5;"> Model Hijab Terbaru dan Terlaris... </h5>
                    
                    <h5 class="ls-s3 text6" style="top:70px; left: 170px; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 2500; scalein : .8; scaleout : .8;"> Bergo Bunga </h5>
                    <h5 class="ls-s3 text6" style="top:120px; left: 380px; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 4500; scalein : .8; scaleout : .8;">  Syria Cristal </h5>
                    <h5 class="ls-s3 text6" style="top:170px; left: 550px; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 6500; scalein : .8; scaleout : .8;">  Sifon Instant </h5>
                    <h5 class="ls-s3 text6" style="top:421px; left: 690px; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 8500; scalein : .8; scaleout : .8;"> Renda Bawah </h5>
                    <h5 class="ls-s3 text6" style="top:471px; left: 890px; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 10500; scalein : .8; scaleout : .8;"> Renda Bunga </h5>
                    
                    <img class="ls-s-1" src="layerslider/gallery/layerslider-on-computer.png" alt="LayerSlider on computer" style="top: 100px; left: 30px; slidedirection : left; slideoutdirection : left; durationin : 1500; delayin : 1000; "> 
                    <img class="ls-s-1" src="layerslider/gallery/layerslider-on-computer2.png" alt="LayerSlider on computer" style="top: 150px; left: 230px; slidedirection : left; slideoutdirection : left; durationin : 1500; delayin : 3000; "> 
                    <img class="ls-s-1" src="layerslider/gallery/layerslider-on-computer3.png" alt="LayerSlider on computer" style="top: 200px; left: 400px; slidedirection : left; slideoutdirection : left; durationin : 1500; delayin : 5000; "> 
                    <img class="ls-s-1" src="layerslider/gallery/layerslider-on-computer4.png" alt="LayerSlider on computer" style="top: 100px; left: 700px; slidedirection : right; slideoutdirection : left; durationin : 1500; delayin : 7000; "> 
                    <img class="ls-s-1" src="layerslider/gallery/layerslider-on-computer5.png" alt="LayerSlider on computer" style="top: 150px; left: 900px; slidedirection : right; slideoutdirection : left; durationin : 1500; delayin : 9000; "> 
                    
                 </div> 
                
                 
            </div>
        </div>
    </section>
    <!-- Slider End--> 
<?php } ?>